import React, { useState } from 'react';
import { Card, Form, Container, Row, Col, Button } from 'react-bootstrap';
import ReactMarkdown from 'react-markdown';
import APIService from '../Common/API';
import { FaCopy, FaFilePdf, FaSpinner, FaFileWord, FaCogs } from 'react-icons/fa';
import PDFGenerator from './PDFGenerator';
import WordGenerator from './WordGenerator';
import AIDisclaimer from './AIDisclaimer';

const ProceduresPractice = () => {
  const [formData, setFormData] = useState({
    entityType: '',
    factsOfCase: '',
    customProcedure: ''
  });

  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState('');


  const entityTypeOptions = [
    'Private Limited Company',
    'Public Limited Company',
    'One Person Company (OPC)',
    'Section 8 Company',
    'LLP',
    'Listed Company',
    'Foreign Company',
    'Producer Company'
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setResponse('');

    // Determine the actual values to use
    const actualProcedure = formData.entityType === 'Other' ? formData.customProcedure : formData.entityType;
    
    const prompt = `You are a Company Law Expert and Trainer.
I want to practice drafting and understanding legal procedure under the Companies Act, 2013 from a Company Secretary's perspective.

Please follow these steps:
1. Based on my inputs, identify the exact statutory procedure.
2. Show the section-wise compliance required and forms to be filed under Companies Act 2013 and rules thereunder or SEBI(in case of Listed Entity type)/ROC rules.[In logical and chronological order].
3. Generate an appropriate draft resolution, filing steps, and expected forms.
4. Display a list of expected supporting documents (for learning - upload not required).

Now take the following inputs and start:
Entity Type: ${actualProcedure}
Facts of the Case:
"${formData.factsOfCase}"

Now generate the final structured practice output in dot note form.

Exclude any introductory notes, prefaces,end notes or disclaimers from the output.

At last include the following line:
This output is generated by AI, kindly verify it by legal professional.
`;

    try {
      await APIService({
        question: prompt,
        onResponse: (data) => {
          setLoading(false);
          if (data && data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts) {
            setResponse(data.candidates[0].content.parts[0].text);
          } else {
            setResponse('Sorry, we couldn\'t generate a response. Please try again.');
          }
        }
      });
    } catch (error) {
      setLoading(false);
      setResponse('An error occurred while processing your request. Please try again.');
    }
  };

  const RedStrong = ({ children }) => {
    return (
    
    <strong style={{ textDecoration: 'underline'}}>{children}</strong>
    
    );
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(response);
    alert('Response copied to clipboard!');
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      handleSubmit(e);
    }
  };

  return (
    <Container fluid className="procedures-practice-container">
      <Row className="justify-content-center">
        <Col lg={10} xl={8}>
          <Card className="main-card shadow-sm">
            <Card.Header className="text-center">
              <h2 className="mb-0">
                <FaCogs className="me-2" />
                Procedures and Practice
              </h2>
              <p className="text-muted mb-0">
                Company Law procedure drafting and compliance practice
              </p>
            </Card.Header>

            <Card.Body>
              <Form onSubmit={handleSubmit} onKeyDown={handleKeyDown}>
                <Row>
                  {/* Entity Type */}
                  <Col md={6}>
                    <Form.Group className="mb-3">
                      <Form.Label><strong>Entity Type</strong></Form.Label>
                      <Form.Select
                        name="entityType"
                        value={formData.entityType}
                        onChange={handleInputChange}
                        required
                      >
                        <option value="">Choose entity type...</option>
                        {entityTypeOptions.map((option, index) => (
                          <option key={index} value={option}>{option}</option>
                        ))}
                      </Form.Select>
                    </Form.Group>
                  </Col>

                  {/* Facts of the Case */}
                  <Col md={12}>
                    <Form.Group className="mb-3">
                      <Form.Label><strong>Facts of the Case</strong></Form.Label>
                      <Form.Control
                        as="textarea"
                        rows={4}
                        name="factsOfCase"
                        value={formData.factsOfCase}
                        onChange={handleInputChange}
                        placeholder="Enter the specific facts and details of the case/situation..."
                        required
                      />
                      <Form.Text className="text-muted">
                        Provide specific details about the situation, company name, dates, and any relevant facts.
                      </Form.Text>
                    </Form.Group>
                  </Col>
                </Row>

                <div className="text-center">
                  <button
                    variant="primary"
                    type="submit"
                    disabled={loading}
                    className="features-button"
                  >
                    {loading ? (
                      <>
                        <FaSpinner className="spinner me-2" />
                        Generating Procedure...
                      </>
                    ) : (
                      <>
                        <FaCogs className="me-2" />
                        Generate Procedure & Practice
                      </>
                    )}
                  </button>
                </div>
              </Form>

              {response && (
                <Card className="response-card mt-4">
                  <Card.Header className="d-flex justify-content-between align-items-center">
                    {/* show the www.ai4cs.in as a link  and in italic*/}
                    <h5 className="mb-0">Procedure & Practice Guide - 
                      <a href="https://www.ai4cs.in" target="_blank" rel="noopener noreferrer" style={{ fontStyle: 'italic', textDecoration: 'underline' }}>(www.ai4cs.in)</a>
                    </h5>
                    <div className="action-buttons">
                      <Button
                        variant="outline-secondary"
                        size="sm"
                        onClick={copyToClipboard}
                        className="me-2"
                      >
                        <FaCopy className="me-1" />
                        Copy
                      </Button>
                      <Button
                        variant="outline-danger"
                        size="sm"
                        onClick={() => {
                          const { generatePDF } = PDFGenerator({
                            content: response,
                            fileName: `procedures-practice-${new Date().toISOString().split('T')[0]}.pdf`,
                            title: "Procedures & Practice Guide"
                          });
                          generatePDF();
                        }}
                        className="me-2"
                      >
                        <FaFilePdf className="me-1" />
                        <span className="d-none d-sm-inline">PDF</span>
                      </Button>
                      <Button
                        variant="outline-success"
                        size="sm"
                        onClick={() => {
                          const { generateWord } = WordGenerator({
                            content: response,
                            fileName: `procedures-practice-${new Date().toISOString().split('T')[0]}.docx`,
                            title: "Procedures & Practice Guide"
                          });
                          generateWord();
                        }}
                      >
                        <FaFileWord className="me-1" />
                        <span className="d-none d-sm-inline">Word</span>
                      </Button>
                    </div>
                  </Card.Header>
                  <Card.Body>
                    <div className="markdown-content">
                      <ReactMarkdown
                        components={{
                          strong: RedStrong,
                        }}
                        style={{
                          whiteSpace: 'pre-wrap',
                          backgroundColor: 'lightgray',
                        }}
                      >{response}</ReactMarkdown>
                    </div>
                  </Card.Body>
                </Card>
              )}
            </Card.Body>
          </Card>

          <AIDisclaimer />
        </Col>
      </Row>
    </Container>
  );
};

export default ProceduresPractice;
